[package]
name = "server"
version.workspace = true
edition.workspace = true

[dependencies]
shared-proto = { path = "../shared-proto" }
tokio = { version = "1", features = ["full"] }
axum = "0.7"
snow = "0.9"
prost = "0.13"
serde = { version = "1", features = ["derive"] }
tracing = "0.1"
tracing-subscriber = "0.3"
